import { HttpInterceptorFn, HttpResponse } from '@angular/common/http';
import { of } from 'rxjs';
import { ICategory, IProduct, ProductSlug } from '../../features/products/product.model';

const MOCK_CATEGORIES: ICategory[] = [
  {
    id: 'cat-1',
    name: 'Whole Spices',
    slug: 'whole-spices',
    description: 'Pure, unground spices sourced directly from farms.',
    short_description: 'Farm-fresh whole spices',
  },
  {
    id: 'cat-2',
    name: 'Ground Spices',
    slug: 'ground-spices',
    description: 'Freshly ground spices for maximum aroma and flavour.',
    short_description: 'Freshly ground for flavour',
  },
  {
    id: 'cat-3',
    name: 'Spice Blends',
    slug: 'spice-blends',
    description: 'Expertly crafted blends of premium spices.',
    short_description: 'Crafted spice blends',
  },
];

const MOCK_PRODUCTS: IProduct[] = [
  {
    id: 'prod-1',
    name: 'HSI Haldi',
    slug: ProductSlug.HALDI,
    generic_name: 'Turmeric Powder',
    description: 'Pure turmeric powder with high curcumin content, sourced from the finest farms.',
    short_description: 'High-curcumin turmeric powder',
    category: MOCK_CATEGORIES[1],
  },
  {
    id: 'prod-2',
    name: 'HSI Mirch',
    slug: ProductSlug.MIRCH,
    generic_name: 'Red Chilli Powder',
    description: 'Bold, vibrant red chilli powder ground from premium dried chillies.',
    short_description: 'Vibrant red chilli powder',
    category: MOCK_CATEGORIES[1],
  },
  {
    id: 'prod-3',
    name: 'HSI Dhania',
    slug: ProductSlug.DHANIA,
    generic_name: 'Coriander Powder',
    description: 'Aromatic coriander powder with a warm, citrusy flavour profile.',
    short_description: 'Aromatic coriander powder',
    category: MOCK_CATEGORIES[1],
  },
  {
    id: 'prod-4',
    name: 'HSI Garam Masala',
    slug: ProductSlug.GARAM_MASALA,
    generic_name: 'Garam Masala Blend',
    description: 'A rich, warming blend of whole spices roasted and ground to perfection.',
    short_description: 'Classic warming spice blend',
    category: MOCK_CATEGORIES[2],
  },
  {
    id: 'prod-5',
    name: 'HSI Jeera',
    slug: ProductSlug.JEERA,
    generic_name: 'Cumin Seeds',
    description: 'Earthy, nutty cumin seeds harvested at peak maturity for full flavour.',
    short_description: 'Earthy whole cumin seeds',
    category: MOCK_CATEGORIES[0],
  },
  {
    id: 'prod-6',
    name: 'HSI Kali Mirch',
    slug: ProductSlug.KALI_MIRCH,
    generic_name: 'Black Pepper',
    description: 'Sharp, pungent black pepper corns with intense heat and complex aroma.',
    short_description: 'Pungent black pepper corns',
    category: MOCK_CATEGORIES[0],
  },
  {
    id: 'prod-7',
    name: 'HSI Elaichi',
    slug: ProductSlug.ELAICHI,
    generic_name: 'Green Cardamom',
    description: 'Fragrant green cardamom pods bursting with sweet, floral notes.',
    short_description: 'Sweet floral cardamom pods',
    category: MOCK_CATEGORIES[0],
  },
  {
    id: 'prod-8',
    name: 'HSI Laung',
    slug: ProductSlug.LAUNG,
    generic_name: 'Cloves',
    description: 'Intensely aromatic whole cloves for rich depth in curries and desserts.',
    short_description: 'Aromatic whole cloves',
    category: MOCK_CATEGORIES[0],
  },
  {
    id: 'prod-9',
    name: 'HSI Dalchini',
    slug: ProductSlug.DALCHINI,
    generic_name: 'Cinnamon Sticks',
    description: 'True Ceylon cinnamon sticks with a delicate, sweet warmth.',
    short_description: 'Delicate Ceylon cinnamon',
    category: MOCK_CATEGORIES[0],
  },
  {
    id: 'prod-10',
    name: 'HSI Methi',
    slug: ProductSlug.METHI,
    generic_name: 'Fenugreek Seeds',
    description: 'Slightly bitter fenugreek seeds that add depth and body to dals and curries.',
    short_description: 'Bitter-nutty fenugreek seeds',
    category: MOCK_CATEGORIES[0],
  },
  {
    id: 'prod-11',
    name: 'HSI Ajwain',
    slug: ProductSlug.AJWAIN,
    generic_name: 'Carom Seeds',
    description: 'Pungent carom seeds with a thyme-like bite, essential for Indian breads.',
    short_description: 'Pungent carom seeds',
    category: MOCK_CATEGORIES[0],
  },
  {
    id: 'prod-12',
    name: 'HSI Saunf',
    slug: ProductSlug.SAUNF,
    generic_name: 'Fennel Seeds',
    description: 'Sweet, anise-flavoured fennel seeds used in cooking and as a mouth freshener.',
    short_description: 'Sweet anise fennel seeds',
    category: MOCK_CATEGORIES[0],
  },
  {
    id: 'prod-13',
    name: 'HSI Hing',
    slug: ProductSlug.HING,
    generic_name: 'Asafoetida Powder',
    description: 'Premium compounded asafoetida with powerful umami depth for tadkas.',
    short_description: 'Powerful asafoetida powder',
    category: MOCK_CATEGORIES[1],
  },
  {
    id: 'prod-14',
    name: 'HSI Amchur',
    slug: ProductSlug.AMCHUR,
    generic_name: 'Dry Mango Powder',
    description: 'Tangy dry mango powder that adds bright acidity to chaat and marinades.',
    short_description: 'Tangy dry mango powder',
    category: MOCK_CATEGORIES[1],
  },
  {
    id: 'prod-15',
    name: 'HSI Kesar',
    slug: ProductSlug.KESAR,
    generic_name: 'Saffron Threads',
    description:
      'Hand-picked Kashmiri saffron threads with deep colour and rich honey-floral aroma.',
    short_description: 'Premium Kashmiri saffron',
    category: MOCK_CATEGORIES[0],
  },
  {
    id: 'prod-16',
    name: 'HSI Javitri',
    slug: ProductSlug.JAVITRI,
    generic_name: 'Mace',
    description: 'Delicate mace blades with warm, slightly sweeter notes than nutmeg.',
    short_description: 'Delicate warm mace blades',
    category: MOCK_CATEGORIES[0],
  },
  {
    id: 'prod-17',
    name: 'HSI Jaiphal',
    slug: ProductSlug.JAIPHAL,
    generic_name: 'Nutmeg',
    description: 'Whole nutmeg with warm, slightly sweet flavour for biryanis and sweets.',
    short_description: 'Warm whole nutmeg',
    category: MOCK_CATEGORIES[0],
  },
  {
    id: 'prod-18',
    name: 'HSI Chaat Masala',
    slug: ProductSlug.CHAAT_MASALA,
    generic_name: 'Chaat Masala Blend',
    description: 'Tangy, peppery blend of amchur, black salt, and cumin for street-food flavour.',
    short_description: 'Tangy street-food spice blend',
    category: MOCK_CATEGORIES[2],
  },
  {
    id: 'prod-19',
    name: 'HSI Kitchen King',
    slug: ProductSlug.KITCHEN_KING,
    generic_name: 'Kitchen King Masala',
    description: 'All-purpose masala blend delivering bold, balanced flavour to everyday curries.',
    short_description: 'All-purpose curry masala',
    category: MOCK_CATEGORIES[2],
  },
  {
    id: 'prod-20',
    name: 'HSI Biryani Masala',
    slug: ProductSlug.BIRYANI_MASALA,
    generic_name: 'Biryani Masala Blend',
    description: 'Fragrant biryani masala with whole spices and saffron-forward notes.',
    short_description: 'Fragrant biryani spice blend',
    category: MOCK_CATEGORIES[2],
  },
  {
    id: 'prod-21',
    name: 'HSI Sabzi Masala',
    slug: ProductSlug.SABZI_MASALA,
    generic_name: 'Vegetable Masala Blend',
    description: 'Light, herbaceous masala crafted to elevate everyday vegetable dishes.',
    short_description: 'Light vegetable spice blend',
    category: MOCK_CATEGORIES[2],
  },
  {
    id: 'prod-22',
    name: 'HSI Tandoori Masala',
    slug: ProductSlug.TANDOORI_MASALA,
    generic_name: 'Tandoori Masala Blend',
    description: 'Smoky, vibrant tandoori masala for authentic clay-oven flavour in every grill.',
    short_description: 'Smoky tandoori spice blend',
    category: MOCK_CATEGORIES[2],
  },
  {
    id: 'prod-23',
    name: 'HSI Pav Bhaji Masala',
    slug: ProductSlug.PAV_BHAJI_MASALA,
    generic_name: 'Pav Bhaji Masala Blend',
    description: 'Rich, tangy pav bhaji masala with the exact street-side Mumbai balance.',
    short_description: 'Mumbai-style pav bhaji blend',
    category: MOCK_CATEGORIES[2],
  },
  {
    id: 'prod-24',
    name: 'HSI Chole Masala',
    slug: ProductSlug.CHOLE_MASALA,
    generic_name: 'Chole Masala Blend',
    description: 'Robust chole masala with dark, smoky depth for authentic Punjabi chickpea curry.',
    short_description: 'Robust Punjabi chole blend',
    category: MOCK_CATEGORIES[2],
  },
];

const MOCK_DB: Record<string, unknown> = {
  '/api/products': MOCK_PRODUCTS,
  '/api/categories': MOCK_CATEGORIES,
};

export const mockInterceptor: HttpInterceptorFn = (req, next) => {
  const path = new URL(req.url, 'http://localhost').pathname;

  if (path in MOCK_DB) {
    return of(new HttpResponse({ status: 200, body: MOCK_DB[path] }));
  }

  return next(req);
};
